// Path: src/constants.tsx
const assets = {
  favicon: '/favicon.ico',
  fonts: {
    InterRegular: '/fonts/Inter-Regular.ttf',
    LibreFranklinRegular: '/fonts/LibreFranklin-Regular.ttf',
    NeueMetanaRegular: '/fonts/NeueMetana-Regular.otf',
    NeueMetanaBold: '/fonts/NeueMetana-Bold.otf',
    BasierCircleRegular: '/fonts/BasierCircle-Regular.otf',
  },
  icons: {
    checkbox: '/icons/checkbox.svg',
    // social
    google: '/icons/google.svg',
  },
  images: {
    app: {
      logo: '/images/app/logo.png',
      image404: '/images/app/404.png',
      defaultAvatar: '/images/app/default-avatar.png',
      toBeRevealedAvatar: '/images/app/to-be-revealed-avatar.png',
    },
    auth: {
      emailSent: '/images/auth/email-sent.png',
      login: '/images/auth/login.png',
    },
    notification: {
      defaultIcon: '/images/notification/default-icon.png',
      defaultWyrIcon: '/images/notification/default-wyr-icon.png',
    },
    quizzes: {
      defaultIcon: '/images/quizzes/default-icon.png',
    },
    chat: {
      bg: '/images/chat/bg.png',
    },
    wyr: {
      random: {
        display: '/images/wyr/random-display.png',
      },
      yours: {
        display: '/images/wyr/yours-display.png',
      },
    },
  },
  deprecated: {
    loginHeroSqaured: '/deprecated/default-squared-mootiez.png',
    defaultReward: '/deprecated/default-reward.png',
    gmPopUp: '/deprecated/gm-popup.png',
  },
  mbti: {
    dIReportPreview: '/mbti/delusion-report-avatar.png',
    wrapImage: '/mbti/wrap-image.png',
    strengthHeart: '/mbti/strength-heart.svg',
    strengthHeart2: '/mbti/strength-heart-2.svg',
    weakness: '/mbti/weak.svg',
    weakness2: '/mbti/weak-2.svg',
    avatar: {
      ENFJ: '/mbti/avatar/ENFJ.png',
      ESFJ: '/mbti/avatar/ESFJ.png',
      INFJ: '/mbti/avatar/INFJ.png',
      ISFJ: '/mbti/avatar/ISFJ.png',
      ENFP: '/mbti/avatar/ENFP.png',
      ESFP: '/mbti/avatar/ESFP.png',
      INFP: '/mbti/avatar/INFP.png',
      ISFP: '/mbti/avatar/ISFP.png',
      ENTJ: '/mbti/avatar/ENTJ.png',
      ESTJ: '/mbti/avatar/ESTJ.png',
      INTJ: '/mbti/avatar/INTJ.png',
      ISTJ: '/mbti/avatar/ISTJ.png',
      ENTP: '/mbti/avatar/ENTP.png',
      ESTP: '/mbti/avatar/ESTP.png',
      INTP: '/mbti/avatar/INTP.png',
      ISTP: '/mbti/avatar/ISTP.png',
    },
    fullReport: {
      ENFJ: '/mbti/full/ENFJ.json',
      ESFJ: '/mbti/full/ESFJ.json',
      INFJ: '/mbti/full/INFJ.json',
      ISFJ: '/mbti/full/ISFJ.json',
      ENFP: '/mbti/full/ENFP.json',
      ESFP: '/mbti/full/ESFP.json',
      INFP: '/mbti/full/INFP.json',
      ISFP: '/mbti/full/ISFP.json',
      ENTJ: '/mbti/full/ENTJ.json',
      ESTJ: '/mbti/full/ESTJ.json',
      INTJ: '/mbti/full/INTJ.json',
      ISTJ: '/mbti/full/ISTJ.json',
      ENTP: '/mbti/full/ENTP.json',
      ESTP: '/mbti/full/ESTP.json',
      INTP: '/mbti/full/INTP.json',
      ISTP: '/mbti/full/ISTP.json',
    },
    report: {
      ENFJ: '/mbti/report/ENFJ.json',
      ESFJ: '/mbti/report/ESFJ.json',
      INFJ: '/mbti/report/INFJ.json',
      ISFJ: '/mbti/report/ISFJ.json',
      ENFP: '/mbti/report/ENFP.json',
      ESFP: '/mbti/report/ESFP.json',
      INFP: '/mbti/report/INFP.json',
      ISFP: '/mbti/report/ISFP.json',
      ENTJ: '/mbti/report/ENTJ.json',
      ESTJ: '/mbti/report/ESTJ.json',
      INTJ: '/mbti/report/INTJ.json',
      ISTJ: '/mbti/report/ISTJ.json',
      ENTP: '/mbti/report/ENTP.json',
      ESTP: '/mbti/report/ESTP.json',
      INTP: '/mbti/report/INTP.json',
      ISTP: '/mbti/report/ISTP.json',
    },
    dI: {
      0: '/mbti/dI/Delusional Index Report-0-10_.jpg',
      // 10: '/mbti/dI/Delusional Index Report-10-20_.jpg',
      20: '/mbti/dI/Delusional Index Report-20-30_.jpg',
      30: '/mbti/dI/Delusional Index Report-30-40_.jpg',
      40: '/mbti/dI/Delusional Index Report-40-50_.jpg',
      50: '/mbti/dI/Delusional Index Report-50-60_.jpg',
      60: '/mbti/dI/Delusional Index Report-60-70_.jpg',
      70: '/mbti/dI/Delusional Index Report-70-80_.jpg',
      80: '/mbti/dI/Delusional Index Report-80-90_.jpg',
      90: '/mbti/dI/Delusional Index Report-90-100_.jpg',
      copywritings: '/mbti/dI/copywritings.json',
    },
  },
  others: {
    tutorial_gif: '/others/tutorial.gif',
    tutorial_mp4: '/others/tutorial.mp4',
  },
  tasks: {
    mbti_test: {
      mbti_banner: '/tasks/mbti-test/mbti-banner.png',
      pronouns_banner: '/tasks/mbti-test/pronouns-banner.png',
      mbti: {
        ENFJ: '/tasks/mbti-test/mbti/ENFJ.png',
        ESFJ: '/tasks/mbti-test/mbti/ESFJ.png',
        INFJ: '/tasks/mbti-test/mbti/INFJ.png',
        ISFJ: '/tasks/mbti-test/mbti/ISFJ.png',
        ENFP: '/tasks/mbti-test/mbti/ENFP.png',
        ESFP: '/tasks/mbti-test/mbti/ESFP.png',
        INFP: '/tasks/mbti-test/mbti/INFP.png',
        ISFP: '/tasks/mbti-test/mbti/ISFP.png',
        ENTJ: '/tasks/mbti-test/mbti/ENTJ.png',
        ESTJ: '/tasks/mbti-test/mbti/ESTJ.png',
        INTJ: '/tasks/mbti-test/mbti/INTJ.png',
        ISTJ: '/tasks/mbti-test/mbti/ISTJ.png',
        ENTP: '/tasks/mbti-test/mbti/ENTP.png',
        ESTP: '/tasks/mbti-test/mbti/ESTP.png',
        INTP: '/tasks/mbti-test/mbti/INTP.png',
        ISTP: '/tasks/mbti-test/mbti/ISTP.png',
      },
      pronouns: {
        e_em_eirs: '/tasks/mbti-test/pronouns/E:em:eirs.png',
        he_him_his: '/tasks/mbti-test/pronouns/He:him:his.png',
        she_her_hers: '/tasks/mbti-test/pronouns/She:her:hers.png',
        they_them_theirs: '/tasks/mbti-test/pronouns/They:them:theirs.png',
        te_tem_ter: '/tasks/mbti-test/pronouns/Te:tem:ter.png',
        ver_vir_vis: '/tasks/mbti-test/pronouns/Ver:vir:vis.png',
        xe_xem_xyrs: '/tasks/mbti-test/pronouns/Xe:xem:xyrs.png',
        ze_hir_hirs: '/tasks/mbti-test/pronouns/Ze:hir:hirs.png',
      },
    },
    chinese_zodiac: {
      banner: '/tasks/chinese-zodiac/banner.png',
      Dog: '/tasks/chinese-zodiac/Dog.png',
      Dragon: '/tasks/chinese-zodiac/Dragon.png',
      Goat: '/tasks/chinese-zodiac/Goat.png',
      Horse: '/tasks/chinese-zodiac/Horse.png',
      Monkey: '/tasks/chinese-zodiac/Monkey.png',
      Ox: '/tasks/chinese-zodiac/Ox.png',
      Pig: '/tasks/chinese-zodiac/Pig.png',
      Rabbit: '/tasks/chinese-zodiac/Rabbit.png',
      Rat: '/tasks/chinese-zodiac/Rat.png',
      Rooster: '/tasks/chinese-zodiac/Rooster.png',
      Snake: '/tasks/chinese-zodiac/Snake.png',
      Tiger: '/tasks/chinese-zodiac/Tiger.png',
    },
    western_zodiac: {
      banner: '/tasks/western-zodiac/banner.png',
      Aquarius: '/tasks/western-zodiac/Aquarius.png',
      Aries: '/tasks/western-zodiac/Aries.png',
      Cancer: '/tasks/western-zodiac/Cancer.png',
      Capricorn: '/tasks/western-zodiac/Capricorn.png',
      Gemini: '/tasks/western-zodiac/Gemini.png',
      Leo: '/tasks/western-zodiac/Leo.png',
      Libra: '/tasks/western-zodiac/Libra.png',
      Pisces: '/tasks/western-zodiac/Pisces.png',
      Sagittarius: '/tasks/western-zodiac/Sagittarius.png',
      Scorpio: '/tasks/western-zodiac/Scorpio.png',
      Taurus: '/tasks/western-zodiac/Taurus.png',
      Virgo: '/tasks/western-zodiac/Virgo.png',
    },
  },
};

export const ButtonID = {
  googleLogin: 'google_login',
  emailLogin: 'magiclink_login',
  appbar: {
    inbox: 'appbar_inbox',
    setting: 'appbar_setting',
    quest: 'appbar_quest',
    quizzes: 'appbar_quizzes',
    would_you_rather: 'appbar_would_you_rather',
    reward: 'appbar_reward',
    profile: 'appbar_profile',
  },
  setting: {
    edit_username: 'setting_edit_username',
    logout: 'setting_logout',
  },
  inbox: {
    card: 'inbox_card',
    landing_back: 'inbox_landing_back',
  },
  di: {
    view_detail: 'di_view_detail',
    tabs: 'di_tabs',
  },
  join: {
    logout: 'join_logout',
    join_mootiez: 'join_mootiez',
  },
  quests: {
    card: 'quest_card',
    other_card_detail: 'quest_other_card_detail',
    follow_instagram: 'quest_follow_instagram',
    open_survey: 'quest_open_survey',
    open_typeform: 'quest_open_typeform',
    typeform: {
      submit: 'quest_typeform_submit',
    },
  },
  rewards: {
    back_to_quests: 'rewards_back_to_quests',
  },
  would_you_rather: {
    copy_link: 'wyr_copy_link',
    share_question: 'wyr_share_question',
    submit_question: 'wyr_submit_question',
    add_question: 'wyr_add_question',
    start_game: 'wyr_start_game',
    pause_game: 'wyr_pause_game',
    restart_game: 'wyr_restart_game',
    submit_answer: 'wyr_submit_answer',
  },

  profile: {
    left: 'profile_left',
    right: 'profile_right',
    stickers: {
      download_sticker: 'profile_stickers_download_sticker',
      confirm_save_sticker: 'profile_stickers_confirm_save_sticker',
      open_tutorial: 'profile_stickers_open_tutorial',
      delete_sticker: 'profile_stickers_delete_sticker',
    },
  },

  already_has_mootiez: {
    enter_app: 'already_has_mootiez_enter_app',
    logout: 'already_has_mootiez_logout',
  },
  gen_mootiez: {
    logout: 'gen_mootiez_logout',
  },
  mootiez_report: {
    enter_app: 'mootiez_report_enter_app',
    back_to_community: 'mootiez_report_back_to_community',
  },
  social_share: {
    share_di: 'Share',
    invite_join_mootiez: 'InviteJoinMootiez',
    copy_to_clipboard_di: 'CopyToClipboard',
    copy_to_clipboard_invite: 'CopyToClipboardInvite',
  },
  functions: {
    share_url: 'ShareUrl',
  },
};
export default assets;
